[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
AFg6K7h4fhy2 = "AFg6K7h4fhy2"
dot_acn = ".acn"
dot_fot = ".fot"
dot_ist = ".ist"

[files]
extend-exclude = [".gitignore", ".pre-commit-config.yaml", "./.github/ISSUE_TEMPLATE/general_issue.md"]
