# About

From the repository's README:

This repository contains most of the source materials (not including references) for the _Genetic Evolution Tournament_ (hereafter referred to as GET), a tournament broadly concerned with human genetic modification and reproduction protocols, for the purposes of both treatment and enhancement (predominantly enhancement). GET is being privately hosted on [Metaculus](https://en.wikipedia.org/wiki/Metaculus). Eventually, Metaculus community forecasts made on GET questions will be ported to this repository and analyzed.

NOTE: All feedback is welcome; however, feedback that enhances (1) the epistemics of claims made in this tournament's questions (and other files), (2) the visibility and or utility of this tournament, or (3) other exact properties of the tournament (such as an additional question or an alteration in the structure) is _particularly_ desired.

## Summary Introduction

* Private tournament on Metaculus
* Focuses on human gene modification and reproduction for enhancing human capabilities
* 150 questions across 5 categories
  * Ethical, Legal, and Societal Implications
  * Technological Advancements and Clinical Applications
  * Regulatory and Policy Developments
  * Accessibility and Demographic Shifts
  * Healthcare and Insurance System Evolution
* 15K USD in prizes
  * 5k USD for forecasting accuracy
  * 10K USD for comments, in stages
* Tentative end date of 2035

To view tournament files, please head to `./GET/source/`

## Example Questions

## Extended Introduction

NOTE: This description, which contains various inadequacies, is a minimally viable placeholder. Beyond the content detailing GET, there are many unsubstantiated claims. At some point, this tournament might be developed into a pre-print, in which case the author will more strongly evidence claims regarding the landscape of current capabilities for human enhancement and treatment via genetic and reproductive means. GET questions often contain references to research literature, but these are far from comprehensive. The Extended Introduction section is liable to change.

This introduction starts with some motivating remarks on possible future(s) for human reproduction and human genetic constitution. Following this, the author briefly describes GET, which is currently under development and due to be released on Metaculus (as a private [tournament](https://en.wikipedia.org/wiki/Prediction_market)) sometime between now and August 2024.

[Scientific progress](https://en.wikipedia.org/wiki/Progress#Scientific_progress) in [genetics](https://en.wikipedia.org/wiki/Genetics), [genetic engineering](https://en.wikipedia.org/wiki/Genetic_engineering), and [assisted-reproduction](https://en.wikipedia.org/wiki/Assisted_reproductive_technology) continues at a rapid and accelerating pace, with current technological capabilities far exceeding those imagined by researchers and policy-makers in [biotechnology](https://en.wikipedia.org/wiki/Biotechnology) at the start of the 21st century.

Frontier events in genetic engineering, such as the [He Jiankui affair](https://en.wikipedia.org/wiki/He_Jiankui_affair), have required all of humanity to consider scenarios and possibilities—ranging the gamut of expected value from fantastical to catastrophic—concerning the manipulation of human biology.

Although extreme-fidelity human gene modification (as in precisely exacting desired genetic outcomes) or, more broadly, [modification of human biology](https://en.wikipedia.org/wiki/Genetic_engineering_techniques) at a caliber similar to what we might expect to be employed in _[Brave New World](https://en.wikipedia.org/wiki/Brave_New_World)_ or _[Gattaca](https://en.wikipedia.org/wiki/Gattaca)_, is yet unrealized, developments in the aforementioned fields steer evermore towards this capacity.

Fortunately, considerable [anticipatory work in ethics](https://en.wikipedia.org/wiki/Bioethics) and governance have coincided with scientific and technological progress in genetic and reproductive research fronts. Ethical work on directed use of technology on human biology has involved some degree of implicit and or explicit scenario analysis, but this analysis (in the author's sampling of the literature) has infrequently employed forecasting.

Handling anticipatory blind spots and reducing uncertainty on futures involving humanity's possible genetic evolution via forecasting seems important for coordination between researchers, the public, and policy-makers in directing outcomes and safeguarding certain aspects of humanity's future.



Despite the expected outcome for GET being that most community traction will occur within the [Effective Altruism](https://forum.effectivealtruism.org/), [Less Wrong](https://www.lesswrong.com/), and [Metaculus](https://www.metaculus.com/questions/) communities, GET seeks to occupy the general niche of uncertainty reduction on futures involving varying levels of human-targeted DNA and assisted-reproduction technologies.

GET will ideally contribute, via the forecasts collected across its lifespan, to a broader scenario modelling effort occurring across discussions on the future(s) of human genetics and reproduction. These forecasts and their analysis might inform individual and policy decision-making on the technologies and procedures involved in human genetics and reproduction.


With respect to the forecasting platform for GET, given both Metaculus's status as a reputable human judgement forecast (HJF) aggregator (this is the author's impression) and the author's familiarity with the site (the author is biased in this way), Metaculus was chosen as the site to host GET. The particular language and norms adopted in public tournaments on Metaculus typically incentivize forecasters to make clear and well-reasoned comments and to forecast as honestly and as accurately as possible. For example Metaculus tournaments, see this [page](https://www.metaculus.com/tournaments/).

GET currently consists of 5 question categories:

* (1) Ethical, Legal, and Societal Implications
* (2) Technological Advancements and Clinical Applications
* (3) Regulatory and Policy Developments
* (4) Accessibility and Demographic Shifts
* (5) Healthcare and Insurance System Evolution

Each category was intended to have between 15 and 25 questions; the intention was to between 75 to 125 questions in total.

To incentivize forecaster participation, there are prizes totaling 15K USD. Prizes are partitioned into a forecasting accuracy component (5k USD), with questions scored via Metaculus's default scoring procedures ([peer scores](https://www.metaculus.com/help/scores-faq/)), and a commenting component (10k USD).

Originally, within the commenting component, 2.5k USD was allocated to comments on questions that are part of the forecasting accuracy component (shorter-term questions) and 7.5k USD was allocated to comments on longer-term questions. However, after some deliberation, a decision was made to break the commenting section of the tournament into 5 stages, each with 2k USD. The tournament is expect to last roughly 10 years. There is the possibility for additional funding altering the structure of the tournament.
