# Administration

The Genetic Evolution Tournament (hereafter GET) is administered by:

* [H559](https://www.metaculus.com/accounts/profile/118777/) (primary administrator)
* James Evans (secondary administrator)

Administration includes:

* Answer participants' questions about GET.
* Resolving GET forecasting questions.
* Allocating prize funds to GET prize holders.
* Continuing the tournament if Metaculus ceases to exist.

* Answering questions the Genetic Evolution Tournament's [GitHub page](https://github.com/AFg6K7h4fhy2/Genetic-Evolution-Tournament) and [Metaculus page](https://www.metaculus.com/tournament/genetic/).
* Resolving Genetic Evolution Tournament questions.
* Allocating prize funds to tournament prize holders.
* Continuing the tournament in edge cases, such if Metaculus were to no longer exist.

To contact:

* Primary Administrator: <AFg6K7h4fhy2@proton.me>
* Secondary Administrator: <keystrike@gmail.com>

To provide feedback, use one of the four avenues:

* [GitHub Discussion Comment](https://github.com/AFg6K7h4fhy2/Genetic-Evolution-Tournament/discussions/28)
* [GitHub Issue](https://github.com/AFg6K7h4fhy2/Genetic-Evolution-Tournament/issues/new/choose)
* [Google Feedback Form]()
* [Metaculus Discussion Comment]()
