# Structure

**Overview**: _The author first explains how GET is set up, temporally speaking. Next, the author explains the size of GET's prize pool. The author closes with considerations for how these aforementioned topics may change._

**Disclaimer**: _If this disclaimer is present, then the below sections are still being developed. Suggestions here would very much be appreciated. Please either make an issue [here](https://github.com/AFg6K7h4fhy2/Genetic-Evolution-Tournament/issues/new/choose), [contact the author](https://genetictournament.com/front_matter/contact.html), or fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScarkulrQarQwt_TbZRTO-iAOv9Ki6zzxl4JjDxDBl2T5YqCQ/viewform?usp=sf_link)._

---

GET is set up in stages:

* Tournament releases early 2025, estimate January 15th.
* _Short-Term Insights_ section begins 2025-01-15, lasts until 2029-12-31.
* _Medium-Term Insights_ section begins 2030-01-01, lasts until 2034-12-31.
* _Long-Term Insights_ section begins 2035-01-01, lasts until 2045-01-01.
* Questions that do not resolve before 2045-01-01 are removed tournament scoring, but not from Metaculus.

Notes on the stages:

* GET is expected to initially have around 150 questions across 5 categories.
* Future questions will likely be added, especially as need arises[^arise].
* Different questions have different hidden[^hidden] periods, based on their close dates.
* (critical) Questions belong to the stage in which they resolve or close.

[^arise]: For example, new technologies or questions conditional on other questions resolving.

[^hidden]: A hidden period on Metaculus is when the Community Forecast is not visible to forecasters. This allows for non-autocorrelated forecasting for at least some period of the question.

Prize structure:

* GET is currently (2024-11-21) funded at PRIZE = 15K USD.
* The prize pool might increase at some point in the future.
* All stages have a commenting prize pool of 2/15 x PRIZE.
* All stages have 10 commenting prizes.
* Awardable comment periods:
  * _Short-Term Insights_: [2025-01-01, 2027-12-31]
  * _Medium-Term Insights_: [2025-01-01, 2032-12-31]
  * _Long-Term Insights_: [2025-01-01, 2032-12-31]
* Awards for comments in each stage are awarded at the end of the stage.
* Forecasting accuracy prize percentages by stage:
  * _Short-Term Insights_: 3.25/15 x PRIZE
  * _Medium-Term Insights_: 2.5/15 x PRIZE
  * _Long-Term Insights_: 1.75/15 x PRIZE
* Forecasting accuracy awards for each stage are also awarded at the end of the stage; these awards cover questions that resolved early i.e. before the stage that contained their close date.
* Conditional on certain questions resolving ambiguously within a stage, some such questions might be created again for a later stage, should the community generally express interest in this.

<!-- There exists some possibility that more funding might become available in the future, so percentages are given for prize quantities.

This prize pool is allocated over several categories: {short-term, medium-term, long-term} X {commenting-prize, forecasting-accuracy-prize}.

One purpose of the tournament is to generate scenarios and discussion surrounding futures involving human enhancement via genetic and reproductive technologies; as such, comments supporting this end are incentivized via commenting prizes.

Another purpose of the tournament is to quantify uncertainty on and predict the occurrence of certain milestones in human enhancement via the aforementioned technologies; as such, accurate and truthful forecasting is incentivized via forecasting prizes. -->

<!-- * Short-Term Insights (35% = 5.25K USD)
  * Period: Years 1-5, i.e. 2025-2029
  * Commenting: 10, 0.2K USD prizes
    * Interval: [2025-01-01, 2027-12-31]
  * Forecasting: Questions in [2025, 2030).
    * Interval: [2025-01-01, 2027-12-31]
  * Award-Date: 2030-01-01
* Medium-Term Insights (30% = 4.50K USD)
  * Period: Years 5-10, i.e. 2030-2034
  * Commenting: 10, 0.2K USD prizes
    * Interval: [2025-01-01, 2032-12-31]
  * Forecasting: Questions in [2030, 2040).
    * Interval: [2025-01-01, 2032-12-31]
  * Award-Date: 2035-01-01
* Long-Term Insights (25% = 3.75K USD)
  * Period: Years 10-15, i.e. 2035-2039
  * Commenting: 10, 0.2K USD prizes
    * Interval: [2025-01-01, 2032-12-31]
  * Forecasting: Questions in [2040, 2100)
    * Interval: [2025-01-01, 2032-12-31]
  * Award-Date: 2040-01-01 -->

Prize restrictions:

* No one participant may receive greater than 1K USD in commenting prizes.
* Commenting prizes will only be distributed within a stage conditional on there being at least 5 comments.
* Commenting prize money not allocated with a stage will be
* Administrators may not receive prizes on comments but may receive forecasting accuracy prizes.

Comment award criteria[^comment_criteria]:

> -   The comment pertains to correct time horizons
-   The comment is well-reasoned and clearly written
-   The comment provides valuable information and reasoning
-   The comment identifies mistakes in the community's reasoning or clearly explains why the author's forecast differs from the community's
-   The comment describes connections between forecasts on different question groups, or inconsistencies between forecasts on different question groups

[^comment_criteria]: At present, the author is deferred to the criteria used in the [OWID tournament](https://www.metaculus.com/tournament/forecasting-Our-World-in-Data/), which is, to some degree, qualitative.
