# When will the first law be enacted anywhere in the world that legally permits the genetic modification of the following human traits?

* Intelligence
* Longevity
* Height
* Eye Color
* Skin Color
* Physical Strength
* Disease Resistance
* Cardiovascular Health
* Metabolism
* Pain Tolerance
* Depression/Anxiety
* Visual Acuity
* Hair Color/Texture
* Resistance To Addiction
* Empathy
* Aggression
* Morality

## Background Information

## Resolution Criteria

### Fine Print

## Notes

The author does not currently know the legal status of genetically engineering humans in all of the Earth's nations. The situation this question focuses on is when nation articulate, in a legal framework, explicit permissions for the use of genetic engineering tools on humans, prenatally. The legality need not be complete; this question will resolve positively if only a particular subset of humans can legally perform the genetic engineering. Perhaps another question can be created for when the first instance of legal private citizenry editing occurs.
