# (Preliminary) Questions

_The following section contains questions for consideration (pruning, subsectioning, and or rephrasing) in GET. Included are questions where some work has already been expended (thus, the author is less inclined to prune these questions), where little work has been expended (full critique welcome here), and questions that already exist on Metaculus. Ratings of importance for the questions is not included here yet but will be once they have been established. Information in brackets are the author's notes._

## Ethical, Legal, & Societal Implications

Will an international treaty [treaty required] regulating human genetic engineering be signed by 20XX? (note: conditional on legal genetic engineering)

Will there cease to be a global moratorium on human germline genome editing by 20XX?

Will a country ban polygenic screening for non-medical traits [exact traits required] by 20XX? (note: explicit ban, any country, specific trait)

Will a significant [definition of significant required] legal case concerning discrimination [definition of discrimination required] based on genetic information [OR genetic engineering?] reach an international court by 20XX?

Will over XX% of countries have laws in place that ban genetic modifications [scope of bans for current countries required] for non-health-related [better phrasing for "non-health-related" required] enhancements by 20XX?

Will more than XX% of the world's population [OR consortium of countries OR specific country] oppose [definition of oppose required] the use of genetic editing for enhancement in public opinion polls [scope of polls required] by 20XX?

Will any country legalize germline genome editing for enhancement by 20XX?

Will the right to refuse genetic modifications be captured in international human rights law [which international human rights law required] by 20XX?

Will genetic engineering technology for cognitive enhancements become a major topic in a national election [measurement of "major topic" required] by 20XX?

Will any country mandate [definition of mandate required] genetic screening for certain genetic diseases by 20XX?

Will religious organizations [scope of religious organizations needed] formally oppose genetic engineering for human enhancement in more than 25 [specific number of countries or jurisdiction scope required] countries by 20XX?

Will polygenic screening for physical or cognitive traits lead to a class-action lawsuit [scope of lawsuit required] in the United States by 20XX?

Will more than 30 countries [scope of countries required] introduce regulations [scope of regulations required] ensuring equal access [scope of equal access required] to genetic enhancement technologies by 20XX?

Will there be a criminalization of unregulated [attempted topic of question is "black market" or "back market"] genetic modifications in over 20 countries [scope of countries required] by 20XX?

Will a genetically modified individual be legally [scope of legal definition required] denied citizenship or human rights by 20XX?

Will more than XX% of countries adopt ethical guidelines [scope of ethical guidelines required] prohibiting the selection of embryos based on non-health-related traits by 20XX?

Will human genome editing be used as a defense in a court of law in a high-profile case [defense in country and publicity of case definitions required] by 20XX?

Will there be widespread protests / riots [scope of civil disobience surrounding topic required] against the use of polygenic screening in schools or workplaces [OR other settings] by 20XX?

Will any country [some scope correction probably useful here] allow parents to choose the sexual orientation of their children via genetic screening or editing by 20XX?

Will more than XX% of the global population use genetic enhancements [measurement for global population and use of genetic enhancement required] that impact physical appearance by 20XX?

In what year will over XX% of countries have a regulatory framework for genetic editing of embryos [current log of countries with genetic editing frameworks required]?

What percentage of the global [OR country OR country consortium] population will support [definition of support required] the right to use genetic engineering for enhancement by 20XX?

In what year will the first international legal case [more detail on international legal case required] be filed concerning genetic discrimination in employment [OR other area]?

By what year will more than XX% of the world’s population [OR country OR country consortium] have undergone some form of genetic enhancement for non-medical purposes [measurement for this question required]?

In what year will more than XX% of healthcare systems globally [scope of global healthcare systems required] implement genetic screening as a routine part [definition of routine part required] of preventive care?

By what year will more than 30 countries [scope of countries required] have established policies [scope of policies required] to protect against genetic inequality [definition of access required] in access to enhancements?

What will be the average cost of a genetic enhancement procedure [stratification by procedure required] in high-income countries [scope and definition of high-income nations required, equivalent question for "low-income" nations required] by 20XX?

What percentage of parents in OECD countries will choose to genetically screen their children for cognitive traits [OR other traits] by 20XX?

By what year will more than XX% of the world's population support laws [definition of support laws required] that prevent genetic discrimination in employment and insurance [OR other areas]?

In what year will a global ethical consensus [scope and definition of consensus requirement] on the limits of genetic editing for non-medical enhancements be reached?

By 20XX, will a major global ethics council [scope of council required] have issued guidelines [scope of guideline required] specifically addressing the ethical use of pre-implantation diagnostics for non-medical trait selection?

Will a public opinion poll in 20XX show that over XX% of the population in at least one G7 country [OR other country designation] supports the use of gene-editing for disease prevention in unborn babies [scope of current opinion polls required]?

By 20XX, will there be a documented legal case where parents are sued [scope of lawsuit required] for not using available gene-editing technologies to prevent a hereditary disease in their child?

Will a country pass legislation by 20XX that requires parental licensing [scope of requirement required] before using pre-implantation diagnostics for selecting embryos based on genetic traits?

Will a social movement advocating for "natural birth" [scope of movement required, definition of advocations required] without genetic modifications gain over 1 million followers [scope of support required] on a major social media platform [platform requirement possibly not necessary] by 20XX?

[move to insurance section] By 20XX, will a major insurance company [scope of major required] in the United States offer a reduced premium for families with genetically edited children to resist common genetic diseases?

Will the World Health Organization (WHO) [OR other organization] establish a special division [log of current divisions or sub-organizations required] by 20XX to monitor and advise on ethical issues related to human genetic enhancement?

By 20XX, will a Nobel Peace Prize [OR other award, catalog of awards required] be awarded to an organization that works to ensure equitable access [outcome or effort based] to gene therapy [OR editing] for populations in developing countries [scope of developing nations required]?

By 20XX, will at least one country have established a "genetic enhancement tax" aimed at subsidizing gene-editing or therapy [scope of interventions required] treatments or enhancements for certain populations [scope of populations required]?

By 20XX, will a court in a major jurisdiction [scope of jurisdiction required] rule that children born with genetic enhancements have the right to know the specifics of their genetic modifications?


## Technological Advancements & Clinical Applications

Will CRISPR-based [OR other DNA-technology, e.g. TALENs] treatment [more specific on treatment, need divide for gene-therapy v. edits] for genetic diseases be available in over XX% of countries by 20XX?

Will a genetic editing technology more precise [definition and measurement of precision required; possible shift to continuous question, "_how much_"] than CRISPR be widely used for human treatments by 20XX?

Will polygenic screening for complex diseases [diseases required, e.g. heart disease, diabetes, ...] become a standard [definition of standard required] part of prenatal care by 20XX?

Will gene-editing therapies for neurodegenerative diseases [disease required, e.g. Alzheimer's, Parkinson's] be approved [scope of approval required] by the FDA [organization(s) approving required] by 20XX?

Will human organs [scope of organs required; enhanced organ function or treatment for organ inadeqaucy?] grown from genetically modified cells be widely used [scope of widely used required] for transplants by 20XX?

Will more than XX% of all cancer therapies [scope of cancer therapies required] involve some form of DNA or genetic engineering by 20XX?

Will gene-editing [scope of gene-editing required] be used to treat autoimmune diseases [diseases required, e.g., Type 1 Diabetes, Rheumatoid Arthritis] in clinical practice [scope of clinical practice required] by 20XX?

Will artificial intelligence be used to automatically [definition of automatically required] design personalized gene therapies [scope of gene therapies required] for patients [patient and or newborns?] by 20XX?

Will a clinical trial [scope of trial required] using gene-editing to treat or prevent aging-related diseases be conducted by 20XX?

Will there be a clinical trial [scope of trial required] using gene-editing for the enhancement of intelligence by 20XX?

Will gene therapies to prevent inherited genetic disorders [disorder scope required, e.g. cystic fibrosis, sickle cell anemia, ...] be standard [definition of standard required] in newborn care in OECD countries [country designation required] by 20XX?

Will more than XX% of hospitals [possibly poor measure for question] in OECD countries [country designation required] use gene-editing to treat infectious diseases [disease scope required, e.g., HIV, hepatitis] by 20XX?

Will polygenic scoring be used to identify genetic predisposition to addiction [check required to see if this has already occurred, if so convert to continuous question] in clinical settings by 20XX?

Will gene-editing be used in clinical trials [scope of trial required] to enhance [scope of enhancement required] immune responses in humans by 20XX?

Will gene-editing be used to increase resistance to viral infections [infection scope required, e.g., influenza, COVID] by 20XX?

Will gene-editing treatments for genetic vision impairments [impairment scope required, e.g., retinitis pigmentosa] be clinically approved [scope of approval required] by 20XX?

Will polygenic risk scoring for mental health [scope of mental health required] be used in over XX% of hospitals [again, hospitals possibly not the best measure] by 20XX?

Will polygenic embryo screening become a standard method [detailed definition of standard required] for selecting embryos in fertility clinics by 20XX?

[question in general needs to be more specific, but hopefully the idea is communicated] Will synthetic DNA or gene circuits be used in human tissues for drug delivery or therapeutic purposes by 20XX?

In what year will gene-editing therapies [scope of therapy and age-of-application required] for muscular dystrophy be available in over XX% of countries?

By what year will the global market for gene-editing therapies surpass XX billion [possibly difficult to measure]?

What percentage of all newborns in OECD countries [country designation required] will undergo polygenic risk screening for disease [can possibly be broken down by disease] by 20XX?

In what year will gene-editing therapies for age-related cognitive decline [OR aging in general] be approved for use in humans?

What percentage of the global population [measurement details required] will have access to gene-editing therapies for non-medical enhancements by 20XX?

By what year will more than XX% of global fertility clinics [measurement details required] offer polygenic embryo screening for traits other than treatment [scope of treatment required]?

What percentage of genetic engineering research funding will be dedicated to gene-editing therapies for metabolic diseases [OR other targets, scope of targets required] by 20XX?

In what year will gene-editing for bone regeneration become a clinical reality [scope of clinical reality required]?

What percentage of the global healthcare budget [measurement details required] will be spent on gene-editing therapies and polygenic screening by 20XX?

By what year will the first CRISPR-based [OR other method] therapy to enhance muscle strength in humans complete a Phase X [scope of trials required] clinical trial?

Will a gene-editing technique for increasing human lifespan enter Phase X [scope of trials required] clinical trials by 20XX?

By 20XX, will there be a commercially available pre-implantation genetic diagnostic test that can screen for over XXX traits [scope of traits required]?

When will a gene therapy aimed [definition of "aimed" required, can be unintentional enhancement release] at enhancing cognitive functions, such as memory or learning speed, be approved for use in any country?

By what year will over 1000 babies born globally [measurement details required] have undergone polygenic screening for enhancement purposes before implantation?

Will there be a breakthrough [definition of breakthrough required] in gene-editing accuracy, achieving a XX.XX% success rate [measurement details required] with no off-target effects [measurement details required], by 20XX?

By 20XX, will scientists have developed a safe, reversible [scope of safe and reversible required] gene-editing system for use in human embryos?

When will the first clinical trial using gene therapy to enhance sensory capabilities [scope of sensory capabilities required e.g., vision, hearing] in humans be initiated?

By 20XX, will gene-editing for cosmetic traits [scope of cosmetic traits required e.g., eye color, height] in embryos be offered by clinics in more than X countries?

Will a gene therapy designed to significantly [definition of significance required] reduce aging effects [OR other effects] in adults be demonstrated as effective in a peer-reviewed study [this designation, peer-reviewed, is main point of this question] by 20XX?

By what year will a gene-editing therapy aimed at enhancing physical endurance or oxygen utilization [details on nature of performance required] in humans be used in a professional athletic context [scope of context required]? _An idea is that there would be sport divisions based on enhancement levels_.

When will the first human trial of gene therapy to enhance resistance to common infectious diseases [scope of diseases required e.g., influenza] be completed [question is practically continuous form of previous binary question]?


Will a new [is "new" needed?] gene-editing tool surpassing CRISPR-Cas9 [OR other DNA technology tool] in efficiency and or precision [definitions of efficiency and precision required] be discovered and described in a scientific journal by 20XX?

By 20XX, will there be an established international registry tracking [scope of tracking required; in clinical context] the health outcomes of individuals who have undergone genetic enhancements?

By what year will a gene therapy [scope of procedures required, outcome is focus] aimed at enhancing metabolic efficiency to prevent obesity be approved by the FDA?

Will researchers demonstrate a successful use of gene-editing to increase human intelligence quotient (IQ) in a peer-reviewed study by 20XX [possibly too similar to other questions]?

[details required, might be subsumed under previous vision question] When will the first application of gene-editing to improve human night vision be tested in a human clinical trial?

By 20XX, will there be a gene-editing therapy [scope of therapy required] that allows for the customization of skin pigmentation, approved for cosmetic use in any country [possibly separate questions; possibly subsumed under previous cosmetic question]?

Will a pre-implantation genetic screening test capable of predicting potential for athletic performance be commercially available by 20XX [claimed v. actual accuracy of test possible distinction]?

By what year will over XXXX individuals have undergone somatic gene-editing for enhancement purposes outside of clinical trials [scope of outside clinical trials needed]?

When will a gene-editing treatment (enhancement?) designed to significantly [definition of significantly needed] enhance human recovery time [measurement details needed] from physical injuries be demonstrated in a Phase X clinical trial?

Will polygenic risk scoring for complex traits like resilience to stress [OR other traits e.g. creativity; measurement details required] be integrated into prenatal screening programs by 20XX?

When will the first successful use of gene-editing to alter human hair growth patterns (baldness prevention) be reported in a scientific journal [possibly subsumed under another question; possibly boundary not scientific journal]?s



## Existing Metaculus Questions

[How many gene-edited babies will have been born worldwide by the end of 2029?](https://www.metaculus.com/questions/3289/how-many-gene-edited-babies-will-have-been-born-worldwide-by-the-end-of-2029/)

[By 20XX, will genetic engineering techniques be available which can raise IQ by 10 points?](https://www.metaculus.com/questions/8515/by-20XX-genetic-engineering-to-raise-iq/)

[By the year 20XX, will any jurisdiction enforce requirements for all births to be genetically engineered?](https://www.metaculus.com/questions/7250/ban-on-genetically-unmodified-humans/)

[When will 100 babies be born whose embryos were selected for genetic scores for intelligence?](https://www.metaculus.com/questions/5525/ivf-based-embryo-selection-for-intelligence/)

[When will some country do widespread embryo selection for intelligence?](https://www.metaculus.com/questions/9785/10-embryo-selection-for-iq-when/)

[When will we see the first viable human case of in vitro gametogenesis?](https://www.metaculus.com/questions/7385/first-human-in-vitro-gametogenesis/)

[When will the first human baby be born, whose embryo was polygenically selected from a cohort of at least 50 simultaneously obtained ova?](https://www.metaculus.com/questions/8910/massive-multiple-embryo-selection/)

[How good will the best published polygenic score be for intelligence in 2026?](https://www.metaculus.com/questions/8090/polygenic-score-for-intelligence-in-2026/)

[Will Republicans support embryo selection for intelligence more than Democrats?](https://www.metaculus.com/questions/9795/republicans-support-es-for-iq-more-than-dems/)

[When will the first baby screened for polygenic traits by Orchid Health be born?](https://www.metaculus.com/questions/7031/first-commercial-polygenic-embryo-screening/)

[Will India be one of the first ten countries to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9594/india-first-10-to-embryo-select-for-iq/)

[Will a European Union member state be one of the first 10 countries to select XX% of its population for IQ?](https://www.metaculus.com/questions/9796/eu-member-first-10-to-embryo-select-for-iq/)

[Will Israel be the first country to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9492/israeli-embryo-selection-for-intelligence/)

[Will China be the first country to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9532/china-leads-in-embryo-selection-for-iq/)

[Will Israel be one of the first ten countries to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9524/israeli-first-10-on-embryo-selection-for-iq/)

[Will the USA be the first country to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9535/usa-leads-in-embryo-selection-for-iq/)

[Will China be one of the first ten countries to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9533/china-first-10-to-embryo-select-for-iq/)

[Will Singapore be the first country to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9491/singaporean-embryo-selection-for-intelligence/)

[Will Singapore be one of the first ten countries to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9525/singapore-first-10-on-embryo-selection-for-iq/)

[Will the USA be one of the first ten countries to embryo select >XX% of its newborns for intelligence?](https://www.metaculus.com/questions/9534/usa-first-10-to-embryo-select-for-iq/)

[By 20XX, Will at least XX% of US births be screened as embryos to detect genetic disorders or disabilities?](https://www.metaculus.com/questions/8505/20-embryo-screened-births-us-by-20XX/)

[Will most of the first 100 IQ-selected "designer babies" be born in China?](https://www.metaculus.com/questions/7925/china-and-designer-babies/)

[Will an anti-discrimination law be enacted to protect U.S. federal employees who have been genetically-edited or screened as embryos by 20XX?](https://www.metaculus.com/questions/9752/protection-for-the-gene-editedscreened/)

[When will a person who was not screened or genetically modified as an embryo file a lawsuit against their parents for not doing so?](https://www.metaculus.com/questions/9793/unscreenunmodified-person-sues-parents/)

[When will a person who was screened or genetically modified as an embryo file a lawsuit against their parents for doing so?](https://www.metaculus.com/questions/9778/screenmodified-person-sues-parents/)

[When will the first human being conceived in vitro from stem cell-derived gametes be born?](https://www.metaculus.com/questions/3034/when-will-the-first-human-baby-from-stem-cell-derived-gametes-be-born/)

[What fraction of babies born in the US in 2029 will have been conceived in vitro?](https://www.metaculus.com/questions/3290/what-fraction-of-babies-born-in-the-us-in-2029-will-have-been-conceived-in-vitro/)

[When will the first example of an entirely extracorporeal human pregnancy conclude with the 'birth' of a healthy, conscious child who lives for a period of at least one year from the date of birth?](https://www.metaculus.com/questions/2769/when-will-the-first-successful-entirely-artificial-extracorporeal-human-pregnancy-conclude/)
